### ISSUE TITLE
Cluster Coordinator election not happening properly

### ISSUE THREAD

**Issue by srishti-gajare** [AlexsJones/kubernetes-nifi-cluster#7]
I am running the set up for 2 node nifi with 3 zookeeper setup. Every time I start up nifi pod both the pods claim as they are the Cluster Coordinator. It works sometimes and sometimes it doesn't. Any idea whats going wrong?

**Comment by AlexsJones** [comment]
I have updated zookeeper project to use the right namespace, and I've fixed the connection string in nifi. Very sorry about this - please try again from scratch.

**Comment by gekosurf** [comment]
NodeClusterCoordinator Failed to determine which node is elected active Cluster Coordinator: ZooKeeper reports the address as nifi-1:2882, but there is no node with this address. Attempted to determine the node's information but failed to retrieve its information due to org.apache.nifi.cluster.protocol.ProtocolException: Failed to create socket due to: java.net.UnknownHostException: nifi-1

**Comment by AlexsJones** [comment]
Can you please try since the `v0.1` release?
